# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2025'
email: marcinjoachimiak@gmail.com
full_name: marcin joachimiak
gh_action_docs_preview: true
gh_action_pypi: true
github_org: realmarcin
license: BSD-3-Clause
project_description: linkml schema for CORAL
project_name: linkml-coral
project_slug: linkml-coral

