generators:
  python:
    target_directory: src/linkml_coral/datamodel
  pydantic:
    target_directory: src/linkml_coral/datamodel
    filename: linkml_coral_pydantic.py
  docs:
    target_directory: docs/elements