generators:
  python:
    target_directory: src/linkml-coral/datamodel
  pydantic:
    target_directory: src/linkml-coral/datamodel
    filename: linkml-coral_pydantic.py
  docs:
    target_directory: docs/elements