erDiagram
Assembly {
}
Bin {
}
Community {
}
Condition {
}
DubSeqLibrary {
}
Gene {
}
Genome {
}
Image {
}
Location {
}
OTU {
}
Process {
}
Protocol {
}
Reads {
}
Sample {
}
Strain {
}
Taxon {
}
TnSeqLibrary {
}